global using Application.Common.Dtos;
global using Application.Common.Factory;
global using Application.Common.Repositories;
global using Dapper;
global using Infrastructure.Common.Factory;
global using Infrastructure.Common.Repositories;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Npgsql;
