name: 'rinha2-jonathanperis-xgh'

# networks:
#   k6:
#   grafana:
#   influxdb:

services:
  webapi1: &webapi1
    # image: jonathanperis/rinha2-back-end-bora-dale-xgh:latest
    build:
      context: ./src/
      dockerfile: ./WebAPI/Dockerfile
      args:
        AOT: true
        TRIM: false
        EXTRA_OPTIMIZE: true
        BUILD_ARCHITECTURE: linux-arm64
        BUILD_CONFIGURATION: Release      
    hostname: webapi1
    container_name: webapi-1
    depends_on:
      - db
    restart: always      
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Username=postgres;Password=postgres;Database=rinha;Minimum Pool Size=10;Maximum Pool Size=10;Multiplexing=true;
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"
    networks:
    - network-bora-dale-xgh

  webapi2:
    <<: *webapi1
    hostname: webapi2
    container_name: webapi-2

  db:
    image: postgres
    hostname: db
    container_name: db-rinha
    restart: always
    depends_on:
      - postgres-exporter      
    volumes:
      - db-rinha-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"      
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "330MB"
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    networks:
    - network-bora-dale-xgh

  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx-rinha
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - webapi1
      - webapi2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"
    networks:
    - network-bora-dale-xgh

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter 
    container_name: postgres-exporter-rinha
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/rinha?sslmode=disable"
    networks:
    - network-bora-dale-xgh

  prometheus:
    image: prom/prometheus
    container_name: prometheus-rinha
    ports:
      - "9090:9090"
    volumes:
      - prometheus-rinha-data:/prometheus
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
    - network-bora-dale-xgh

  grafana:
    # image: grafana/grafana-oss
    image: grafana/grafana
    container_name: grafana-rinha
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
      - "./grafana/dashboards/:/var/lib/grafana/dashboards/"
    depends_on:
      - prometheus
    networks:
    - network-bora-dale-xgh

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin-rinha
  #   depends_on:
  #     - db    
  #   ports:
  #     - "5050:5050"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #     PGADMIN_LISTEN_PORT: 5050
  #   networks:
  #   - network-bora-dale-xgh

  k6:
    # image: grafana/k6
    build:
      context: ./test/
      dockerfile: ./stress-test/Dockerfile    
    container_name: k6
    environment:
      - BASE_URL=http://nginx:9999
      - K6_WEB_DASHBOARD=true
      - K6_INFLUXDB_ADDR=http://influxdb:8086
      # - K6_OUT=xk6-influxdb=http://influxdb:8086
      - K6_INFLUXDB_ORGANIZATION=rinha
      - K6_INFLUXDB_BUCKET=demo
      - K6_INFLUXDB_INSECURE=true
      - K6_INFLUXDB_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==      
    volumes:
      - "./test/stress-test:/app"
    working_dir: /app
    tty: true
    stdin_open: true
    depends_on:
      - nginx
      - webapi1
      - webapi2
      - db
      - grafana 
      - influxdb      
    entrypoint: ["/bin/sh", "/app/init-test.sh"]
    ports:
      - "5665:5665"
    networks:
      - network-bora-dale-xgh

  influxdb:
    image: influxdb:2.0-alpine
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=VG3AfE!pz8x7
      - DOCKER_INFLUXDB_INIT_ORG=rinha
      - DOCKER_INFLUXDB_INIT_BUCKET=demo
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==
    networks:
      - network-bora-dale-xgh

networks:
  network-bora-dale-xgh:
    driver: bridge

volumes:
  db-rinha-data:
    driver: local
  prometheus-rinha-data:
    driver: local