version: '3.9'
name: 'rinha2-jonathanperis-xgh'

services:
  webapi1: &webapi1
    # image: jonathanperis/rinha2-back-end-bora-dale-xgh:latest
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile    
    hostname: webapi1
    container_name: webapi-1
    depends_on:
      - db
    restart: always      
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Username=postgres;Password=postgres;Database=rinha;Minimum Pool Size=10;Maximum Pool Size=10;Multiplexing=true;
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"
  
  webapi2:
    <<: *webapi1
    hostname: webapi2
    container_name: webapi-2

  db:
    image: postgres
    hostname: db
    container_name: db-rinha
    restart: always
    depends_on:
      - postgres-exporter      
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0

  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx-rinha
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - webapi1
      - webapi2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/rinha?sslmode=disable"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
      image: grafana/grafana-oss
      ports:
        - "3000:3000"
      volumes:
        # https://grafana.com/docs/grafana/latest/administration/provisioning/
        - "./grafana/provisioning/:/etc/grafana/provisioning/"
        - "./grafana/dashboards/:/var/lib/grafana/dashboards/"
      depends_on:
        - prometheus

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"

networks: 
  default:
    driver: bridge
    name: network-bora-dale-xgh