@HostAddress = http://localhost:5147

GET {{HostAddress}}/extrato/1
# Accept: application/json

###

POST {{HostAddress}}/transacoes/1
# Accept: application/json
Content-Type: application/json

{
  
}

###
