global using Application.Common.Dtos;
global using Application.Common.Factory;
global using Application.Common.Models;
global using Application.Common.Repositories;
global using Mediator;
global using Microsoft.Extensions.DependencyInjection;
global using Npgsql;
global using System.ComponentModel.DataAnnotations;
global using System.Text.Json.Serialization;
