name: Build, Publish and Deploy image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  RINHA_GATLING_VERSION: 3.10.3
  RINHA_DIR: rinha-de-backend-2024-q1

jobs:
  setup-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./src/WebAPI"

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Install dependencies
      run: dotnet restore        

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        updateAssemblyInfo: true

    - name: Build project
      run: dotnet build --configuration Release --no-restore /p:Version=${{ env.GitVersion_SemVer }} /p:SourceLinkCreate=true /p:PublicRelease=true

  build-push-image:
    needs: setup-build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: ./src/WebAPI/Dockerfile
        tags: jonathanperis/rinha2-back-end-bora-dale-xgh:latest

  container-test:
    runs-on: ubuntu-latest
    needs: build-push-image
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: test
      run: |
        docker-compose -f ./prod/docker-compose.yml up -d
        sleep 10
        for i in {1..20}; do
          if curl --silent --fail http://localhost:9999/clientes/1/extrato; then
            echo " - Request successful!"
            break
          else
            echo " - Request failed, retrying..."
            sleep 2
          fi
        done

  load-test:
    runs-on: ubuntu-latest
    needs: container-test
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: running everything
        run: docker-compose -f ./prod/docker-compose.yml up --build --force-recreate -d

      - name: test
        run: |
          git clone --depth 1 --single-branch -b main https://github.com/zanfranceschi/rinha-de-backend-2024-q1.git
          wget -P $RINHA_DIR https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/$RINHA_GATLING_VERSION/gatling-charts-highcharts-bundle-$RINHA_GATLING_VERSION-bundle.zip
          unzip -d $RINHA_DIR $RINHA_DIR/gatling-charts-highcharts-bundle-$RINHA_GATLING_VERSION-bundle.zip
          ./bin/executar-teste-local

          echo GATLING_REPORT=$(ls $RINHA_DIR/load-test/user-files/results | sort | head -n 1) >> $GITHUB_ENV

      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: upload test results
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.RINHA_DIR }}/load-test/user-files/results/${{ env.GATLING_REPORT }}
          retention-days: 2
